apiVersion: v1
kind: Service
metadata:
  name: hw46-nginx-nodeport
  namespace: hw46
spec:
  type: NodePort
  selector:
    app: hw46-nginx
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30080
      protocol: TCP
