apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hw46-pvc
  namespace: hw46
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: yc-network-hdd
  resources:
    requests:
      storage: 1Gi
