id: dnsb8fm4o13dr2g21vj5
folder_id: b1gcijdrjlf3m935prl2
created_at: "2026-03-29T14:31:50.579Z"
name: typespeedarena-zone
description: Публичная DNS-зона для домена typespeedarena.ru
zone: typespeedarena.ru.
public_visibility: {}

