Server=zabbix-server
ServerActive=zabbix-server
Hostname=Zabbix server

# Переопределяем фильтр: агент будет находить ТОЛЬКО контейнеры с этой меткой Docker
Plugins.Docker.Options.Filters=label=zabbix.monitor=true