input {
  beats {
    port => 5044
  }
}

filter {
  if [message] =~ "^\{.*\}$" {
    json {
      source => "message"
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    user => "${LOGSTASH_USERNAME}"
    password => "${LOGSTASH_PASSWORD}"
    index => "docker-logs-%{+YYYY.MM.dd}"
  }

  stdout {
    codec => rubydebug
  }
}
