#cloud-config
package_update: true
packages:
  - nginx

write_files:
  - path: /var/www/html/index.html
    permissions: '0644'
    owner: root:root
    content: |
      <html>
        <head><title>HW43</title></head>
        <body>
          <h1>HW43 web server is running</h1>
          <p>This VM was created by Terraform in Yandex Cloud.</p>
        </body>
      </html>

runcmd:
  - systemctl enable nginx
  - systemctl restart nginx