name: terraform

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  plan: 
    name: terraform_plan
    runs-on: ubuntu-latest
    env: 
      YC_CLOUD_ID: ${{ secrets.YC_CLOUD_ID }}
      YC_FOLDER_ID: ${{ secrets.YC_FOLDER_ID }}
      YC_SERVICE_ACCOUNT_KEY_FILE: ${{ github.workspace }}/terraform-HW/HW41/key.json

    defaults:
      run: 
        shell: bash
        working-directory: terraform-HW/HW41

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup terraform
        uses: hashicorp/setup-terraform@v3

      - name: prepare yc creads
        run: echo '${{ secrets.YC_SA_KEY_JSON_ID }}' > ${{ github.workspace }}/terraform-HW/HW41/key.json

      - name: key_debag
        run:  ls -l ${{ github.workspace }}/key.json

#      - name: export s3 creads
#        run: |
#         echo '' > /tmp/key.json     
#

      - name: Terraform fmt check
        run: terraform fmt -check -recursive

      - name: Terraform init
        run: terraform init

      - name: Terraform plan
        if: github.event_name == 'pull_request'
        run: terraform plan
